// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: HotelRoomThermostat

#include "ui.h"

lv_obj_t * ui_Settings3 = NULL;
lv_obj_t * ui_LabelBrightHigh = NULL;
lv_obj_t * ui_SliderBrightHigh = NULL;
lv_obj_t * ui_LabelBrightLow = NULL;
lv_obj_t * ui_SliderBrightLow = NULL;
lv_obj_t * ui_LabelTimeout = NULL;
lv_obj_t * ui_DropTimeout = NULL;
lv_obj_t * ui_LabelModbus = NULL;
lv_obj_t * ui_SpinModbusAddr = NULL;
lv_obj_t * ui_BtnModbusDec = NULL;
lv_obj_t * ui_LabelBtnModbusDec = NULL;
lv_obj_t * ui_BtnModbusInc = NULL;
lv_obj_t * ui_LabelBtnModbusInc = NULL;
lv_obj_t * ui_SwitchStartAp = NULL;
lv_obj_t * ui_LabelStartAp = NULL;
lv_obj_t * ui_BtnSave3 = NULL;
lv_obj_t * ui_LabelBtnSave3 = NULL;
lv_obj_t * ui_BtnNext3 = NULL;
lv_obj_t * ui_LabelBtnNext3 = NULL;
// event funtions
void ui_event_Settings3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        settings3_loaded_cb(e);
    }
}

void ui_event_SliderBrightHigh(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        action_bright_high_changed(e);
    }
}

void ui_event_SliderBrightLow(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        action_bright_low_changed(e);
    }
}

void ui_event_DropTimeout(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        action_timeout_changed(e);
    }
}

void ui_event_SpinModbusAddr(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        action_modbus_changed(e);
    }
}

void ui_event_BtnModbusDec(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_spinbox_step(ui_SpinModbusAddr, -1);
    }
    if(event_code == LV_EVENT_LONG_PRESSED_REPEAT) {
        _ui_spinbox_step(ui_SpinModbusAddr, -1);
    }
}

void ui_event_BtnModbusInc(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_spinbox_step(ui_SpinModbusAddr, 1);
    }
    if(event_code == LV_EVENT_LONG_PRESSED_REPEAT) {
        _ui_spinbox_step(ui_SpinModbusAddr, 1);
    }
}

void ui_event_SwitchStartAp(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        action_start_wifi_manager(e);
    }
}

void ui_event_BtnSave3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        action_save_and_exit(e);
    }
}

void ui_event_BtnNext3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Settings1, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Settings1_screen_init);
    }
}

// build funtions

void ui_Settings3_screen_init(void)
{
    ui_Settings3 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Settings3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Settings3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Settings3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelBrightHigh = lv_label_create(ui_Settings3);
    lv_obj_set_width(ui_LabelBrightHigh, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelBrightHigh, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelBrightHigh, 20);
    lv_obj_set_y(ui_LabelBrightHigh, 20);
    lv_label_set_text(ui_LabelBrightHigh, "Brightness High");

    ui_SliderBrightHigh = lv_slider_create(ui_Settings3);
    lv_slider_set_range(ui_SliderBrightHigh, 0, 100);
    lv_slider_set_value(ui_SliderBrightHigh, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SliderBrightHigh) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_SliderBrightHigh, 0,
                                                                                                     LV_ANIM_OFF);
    lv_obj_set_width(ui_SliderBrightHigh, 440);
    lv_obj_set_height(ui_SliderBrightHigh, 20);
    lv_obj_set_x(ui_SliderBrightHigh, 0);
    lv_obj_set_y(ui_SliderBrightHigh, 50);
    lv_obj_set_align(ui_SliderBrightHigh, LV_ALIGN_TOP_MID);

    ui_LabelBrightLow = lv_label_create(ui_Settings3);
    lv_obj_set_width(ui_LabelBrightLow, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelBrightLow, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelBrightLow, 20);
    lv_obj_set_y(ui_LabelBrightLow, 100);
    lv_label_set_text(ui_LabelBrightLow, "Brightness Low (Screensaver)");

    ui_SliderBrightLow = lv_slider_create(ui_Settings3);
    lv_slider_set_value(ui_SliderBrightLow, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_SliderBrightLow) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_SliderBrightLow, 0,
                                                                                                    LV_ANIM_OFF);
    lv_obj_set_width(ui_SliderBrightLow, 440);
    lv_obj_set_height(ui_SliderBrightLow, 20);
    lv_obj_set_x(ui_SliderBrightLow, 0);
    lv_obj_set_y(ui_SliderBrightLow, 130);
    lv_obj_set_align(ui_SliderBrightLow, LV_ALIGN_TOP_MID);

    ui_LabelTimeout = lv_label_create(ui_Settings3);
    lv_obj_set_width(ui_LabelTimeout, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTimeout, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTimeout, 20);
    lv_obj_set_y(ui_LabelTimeout, 200);
    lv_label_set_text(ui_LabelTimeout, "Screensaver Timeout");

    ui_DropTimeout = lv_dropdown_create(ui_Settings3);
    lv_dropdown_set_options(ui_DropTimeout, "30s\n60s\n120s");
    lv_obj_set_width(ui_DropTimeout, 200);
    lv_obj_set_height(ui_DropTimeout, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DropTimeout, -20);
    lv_obj_set_y(ui_DropTimeout, 190);
    lv_obj_set_align(ui_DropTimeout, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_DropTimeout, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_LabelModbus = lv_label_create(ui_Settings3);
    lv_obj_set_width(ui_LabelModbus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelModbus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelModbus, 20);
    lv_obj_set_y(ui_LabelModbus, 280);
    lv_label_set_text(ui_LabelModbus, "Modbus Address");

    ui_SpinModbusAddr = lv_spinbox_create(ui_Settings3);
    lv_obj_set_width(ui_SpinModbusAddr, 150);
    lv_obj_set_height(ui_SpinModbusAddr, 50);
    lv_obj_set_x(ui_SpinModbusAddr, -40);
    lv_obj_set_y(ui_SpinModbusAddr, 270);
    lv_obj_set_align(ui_SpinModbusAddr, LV_ALIGN_TOP_RIGHT);
    lv_spinbox_set_digit_format(ui_SpinModbusAddr, 3, 0);
    lv_spinbox_set_range(ui_SpinModbusAddr, 1, 247);
    lv_spinbox_set_cursor_pos(ui_SpinModbusAddr, 1 - 1);
    lv_obj_set_style_text_align(ui_SpinModbusAddr, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SpinModbusAddr, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnModbusDec = lv_btn_create(ui_Settings3);
    lv_obj_set_width(ui_BtnModbusDec, 50);
    lv_obj_set_height(ui_BtnModbusDec, 50);
    lv_obj_set_x(ui_BtnModbusDec, -170);
    lv_obj_set_y(ui_BtnModbusDec, 270);
    lv_obj_set_align(ui_BtnModbusDec, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_BtnModbusDec, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnModbusDec, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelBtnModbusDec = lv_label_create(ui_BtnModbusDec);
    lv_obj_set_width(ui_LabelBtnModbusDec, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelBtnModbusDec, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelBtnModbusDec, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelBtnModbusDec, "-");
    lv_obj_set_style_text_font(ui_LabelBtnModbusDec, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnModbusInc = lv_btn_create(ui_Settings3);
    lv_obj_set_width(ui_BtnModbusInc, 50);
    lv_obj_set_height(ui_BtnModbusInc, 50);
    lv_obj_set_x(ui_BtnModbusInc, -20);
    lv_obj_set_y(ui_BtnModbusInc, 270);
    lv_obj_set_align(ui_BtnModbusInc, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_BtnModbusInc, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnModbusInc, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelBtnModbusInc = lv_label_create(ui_BtnModbusInc);
    lv_obj_set_width(ui_LabelBtnModbusInc, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelBtnModbusInc, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelBtnModbusInc, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelBtnModbusInc, "+");
    lv_obj_set_style_text_font(ui_LabelBtnModbusInc, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SwitchStartAp = lv_switch_create(ui_Settings3);
    lv_obj_set_width(ui_SwitchStartAp, 50);
    lv_obj_set_height(ui_SwitchStartAp, 25);
    lv_obj_set_x(ui_SwitchStartAp, 20);
    lv_obj_set_y(ui_SwitchStartAp, 330);

    ui_LabelStartAp = lv_label_create(ui_Settings3);
    lv_obj_set_width(ui_LabelStartAp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelStartAp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelStartAp, 80);
    lv_obj_set_y(ui_LabelStartAp, 335);
    lv_label_set_text(ui_LabelStartAp, "START WIFI AP");

    ui_BtnSave3 = lv_btn_create(ui_Settings3);
    lv_obj_set_width(ui_BtnSave3, 140);
    lv_obj_set_height(ui_BtnSave3, 60);
    lv_obj_set_x(ui_BtnSave3, 20);
    lv_obj_set_y(ui_BtnSave3, -20);
    lv_obj_set_align(ui_BtnSave3, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_BtnSave3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnSave3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelBtnSave3 = lv_label_create(ui_BtnSave3);
    lv_obj_set_width(ui_LabelBtnSave3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelBtnSave3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelBtnSave3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelBtnSave3, "SAVE");
    lv_obj_set_style_text_font(ui_LabelBtnSave3, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnNext3 = lv_btn_create(ui_Settings3);
    lv_obj_set_width(ui_BtnNext3, 140);
    lv_obj_set_height(ui_BtnNext3, 60);
    lv_obj_set_x(ui_BtnNext3, -20);
    lv_obj_set_y(ui_BtnNext3, -20);
    lv_obj_set_align(ui_BtnNext3, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_add_flag(ui_BtnNext3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnNext3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelBtnNext3 = lv_label_create(ui_BtnNext3);
    lv_obj_set_width(ui_LabelBtnNext3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelBtnNext3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelBtnNext3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelBtnNext3, "NEXT");
    lv_obj_set_style_text_font(ui_LabelBtnNext3, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_SliderBrightHigh, ui_event_SliderBrightHigh, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SliderBrightLow, ui_event_SliderBrightLow, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_DropTimeout, ui_event_DropTimeout, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SpinModbusAddr, ui_event_SpinModbusAddr, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnModbusDec, ui_event_BtnModbusDec, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnModbusInc, ui_event_BtnModbusInc, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SwitchStartAp, ui_event_SwitchStartAp, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnSave3, ui_event_BtnSave3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnNext3, ui_event_BtnNext3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Settings3, ui_event_Settings3, LV_EVENT_ALL, NULL);

}

void ui_Settings3_screen_destroy(void)
{
    if(ui_Settings3) lv_obj_del(ui_Settings3);

    // NULL screen variables
    ui_Settings3 = NULL;
    ui_LabelBrightHigh = NULL;
    ui_SliderBrightHigh = NULL;
    ui_LabelBrightLow = NULL;
    ui_SliderBrightLow = NULL;
    ui_LabelTimeout = NULL;
    ui_DropTimeout = NULL;
    ui_LabelModbus = NULL;
    ui_SpinModbusAddr = NULL;
    ui_BtnModbusDec = NULL;
    ui_LabelBtnModbusDec = NULL;
    ui_BtnModbusInc = NULL;
    ui_LabelBtnModbusInc = NULL;
    ui_SwitchStartAp = NULL;
    ui_LabelStartAp = NULL;
    ui_BtnSave3 = NULL;
    ui_LabelBtnSave3 = NULL;
    ui_BtnNext3 = NULL;
    ui_LabelBtnNext3 = NULL;

}

void ui_Settings3_screen_relocalize(void)
{
    // label widgets on screen

}
