// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: HotelRoomThermostat

#include "ui.h"
#include "settings_limits.h"
extern lv_obj_t *ui_DropSelectTheme;
extern void action_theme_changed(lv_event_t *e);

lv_obj_t * ui_Settings2 = NULL;
lv_obj_t * ui_LabelHysteresis = NULL;
lv_obj_t * ui_DropHysteresis = NULL;
lv_obj_t * ui_LabelStageStep = NULL;
lv_obj_t * ui_DropStageStep = NULL;
lv_obj_t * ui_LabelSensorOffset = NULL;
lv_obj_t * ui_SpinSensorOffset = NULL;
lv_obj_t * ui_BtnOffsetDec = NULL;
lv_obj_t * ui_LabelBtnOffsetDec = NULL;
lv_obj_t * ui_BtnOffsetInc = NULL;
lv_obj_t * ui_LabelBtnOffsetInc = NULL;
lv_obj_t * ui_BtnSave2 = NULL;
lv_obj_t * ui_LabelBtnSave2 = NULL;
lv_obj_t * ui_BtnNext2 = NULL;
lv_obj_t * ui_LabelBtnNext2 = NULL;
// event funtions
void ui_event_Settings2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        settings2_loaded_cb(e);
    }
}

void ui_event_DropHysteresis(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        action_hysteresis_changed(e);
    }
}

void ui_event_DropStageStep(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        action_stage_step_changed(e);
    }
}

void ui_event_SpinSensorOffset(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        action_offset_changed(e);
    }
}

void ui_event_BtnOffsetDec(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_spinbox_step(ui_SpinSensorOffset, -1);
    }
    if(event_code == LV_EVENT_LONG_PRESSED_REPEAT) {
        _ui_spinbox_step(ui_SpinSensorOffset, -1);
    }
}

void ui_event_BtnOffsetInc(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_spinbox_step(ui_SpinSensorOffset, 1);
    }
    if(event_code == LV_EVENT_LONG_PRESSED_REPEAT) {
        _ui_spinbox_step(ui_SpinSensorOffset, 1);
    }
}

void ui_event_BtnSave2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        action_save_and_exit(e);
    }
}

void ui_event_BtnNext2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Settings3, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Settings3_screen_init);
    }
}

// build funtions

void ui_Settings2_screen_init(void)
{
    ui_Settings2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Settings2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Settings2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Settings2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Settings2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelHysteresis = lv_label_create(ui_Settings2);
    lv_obj_set_width(ui_LabelHysteresis, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelHysteresis, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelHysteresis, 20);
    lv_obj_set_y(ui_LabelHysteresis, 30);
    lv_label_set_text(ui_LabelHysteresis, "Hysteresis (Base)");

    ui_DropHysteresis = lv_dropdown_create(ui_Settings2);
    lv_dropdown_set_options(ui_DropHysteresis, "0.2\n0.3\n0.4\n0.5\n0.6\n0.7\n0.8\n0.9\n1.0\n1.1\n1.2\n1.3\n1.4\n1.5\n1.6\n1.7\n1.8\n1.9\n2.0");
    lv_obj_set_width(ui_DropHysteresis, 200);
    lv_obj_set_height(ui_DropHysteresis, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DropHysteresis, -20);
    lv_obj_set_y(ui_DropHysteresis, 20);
    lv_obj_set_align(ui_DropHysteresis, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_DropHysteresis, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_LabelStageStep = lv_label_create(ui_Settings2);
    lv_obj_set_width(ui_LabelStageStep, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelStageStep, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelStageStep, 20);
    lv_obj_set_y(ui_LabelStageStep, 110);
    lv_label_set_text(ui_LabelStageStep, "Stage Step");

    ui_DropStageStep = lv_dropdown_create(ui_Settings2);
    lv_dropdown_set_options(ui_DropStageStep, "0.5\n0.6\n0.7\n0.8\n0.9\n1.0\n1.1\n1.2\n1.3\n1.4\n1.5\n1.6\n1.7\n1.8\n1.9\n2.0\n2.1\n2.2\n2.3\n2.4\n2.5");
    lv_obj_set_width(ui_DropStageStep, 200);
    lv_obj_set_height(ui_DropStageStep, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DropStageStep, -20);
    lv_obj_set_y(ui_DropStageStep, 100);
    lv_obj_set_align(ui_DropStageStep, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_DropStageStep, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_LabelSensorOffset = lv_label_create(ui_Settings2);
    lv_obj_set_width(ui_LabelSensorOffset, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSensorOffset, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSensorOffset, 20);
    lv_obj_set_y(ui_LabelSensorOffset, 190);
    lv_label_set_text(ui_LabelSensorOffset, "Sensor Offset (°C)");

    ui_SpinSensorOffset = lv_spinbox_create(ui_Settings2);
    lv_obj_set_width(ui_SpinSensorOffset, 150);
    lv_obj_set_height(ui_SpinSensorOffset, 50);
    lv_obj_set_x(ui_SpinSensorOffset, -40);
    lv_obj_set_y(ui_SpinSensorOffset, 180);
    lv_obj_set_align(ui_SpinSensorOffset, LV_ALIGN_TOP_RIGHT);
    lv_spinbox_set_digit_format(ui_SpinSensorOffset, 3, 2);
    lv_spinbox_set_range(ui_SpinSensorOffset, SENSOR_OFFSET_MIN_X10, SENSOR_OFFSET_MAX_X10);
    lv_spinbox_set_cursor_pos(ui_SpinSensorOffset, 1 - 1);
    lv_obj_set_style_text_align(ui_SpinSensorOffset, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SpinSensorOffset, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnOffsetDec = lv_btn_create(ui_Settings2);
    lv_obj_set_width(ui_BtnOffsetDec, 50);
    lv_obj_set_height(ui_BtnOffsetDec, 50);
    lv_obj_set_x(ui_BtnOffsetDec, -170);
    lv_obj_set_y(ui_BtnOffsetDec, 180);
    lv_obj_set_align(ui_BtnOffsetDec, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_BtnOffsetDec, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnOffsetDec, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelBtnOffsetDec = lv_label_create(ui_BtnOffsetDec);
    lv_obj_set_width(ui_LabelBtnOffsetDec, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelBtnOffsetDec, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelBtnOffsetDec, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelBtnOffsetDec, "-");
    lv_obj_set_style_text_font(ui_LabelBtnOffsetDec, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnOffsetInc = lv_btn_create(ui_Settings2);
    lv_obj_set_width(ui_BtnOffsetInc, 50);
    lv_obj_set_height(ui_BtnOffsetInc, 50);
    lv_obj_set_x(ui_BtnOffsetInc, -20);
    lv_obj_set_y(ui_BtnOffsetInc, 180);
    lv_obj_set_align(ui_BtnOffsetInc, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_BtnOffsetInc, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnOffsetInc, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelBtnOffsetInc = lv_label_create(ui_BtnOffsetInc);
    lv_obj_set_width(ui_LabelBtnOffsetInc, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelBtnOffsetInc, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelBtnOffsetInc, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelBtnOffsetInc, "+");
    lv_obj_set_style_text_font(ui_LabelBtnOffsetInc, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnSave2 = lv_btn_create(ui_Settings2);
    lv_obj_set_width(ui_BtnSave2, 140);
    lv_obj_set_height(ui_BtnSave2, 60);
    lv_obj_set_x(ui_BtnSave2, 20);
    lv_obj_set_y(ui_BtnSave2, -20);
    lv_obj_set_align(ui_BtnSave2, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_BtnSave2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnSave2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelBtnSave2 = lv_label_create(ui_BtnSave2);
    lv_obj_set_width(ui_LabelBtnSave2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelBtnSave2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelBtnSave2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelBtnSave2, "SAVE");
    lv_obj_set_style_text_font(ui_LabelBtnSave2, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnNext2 = lv_btn_create(ui_Settings2);
    lv_obj_set_width(ui_BtnNext2, 140);
    lv_obj_set_height(ui_BtnNext2, 60);
    lv_obj_set_x(ui_BtnNext2, -20);
    lv_obj_set_y(ui_BtnNext2, -20);
    lv_obj_set_align(ui_BtnNext2, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_add_flag(ui_BtnNext2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnNext2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelBtnNext2 = lv_label_create(ui_BtnNext2);
    lv_obj_set_width(ui_LabelBtnNext2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelBtnNext2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelBtnNext2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelBtnNext2, "NEXT");
    lv_obj_set_style_text_font(ui_LabelBtnNext2, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_DropHysteresis, ui_event_DropHysteresis, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_DropStageStep, ui_event_DropStageStep, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SpinSensorOffset, ui_event_SpinSensorOffset, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnOffsetDec, ui_event_BtnOffsetDec, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnOffsetInc, ui_event_BtnOffsetInc, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnSave2, ui_event_BtnSave2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnNext2, ui_event_BtnNext2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Settings2, ui_event_Settings2, LV_EVENT_ALL, NULL);

    lv_obj_t *theme_label=lv_label_create(ui_Settings2);
    lv_label_set_text(theme_label, "Theme");
    lv_obj_set_pos(theme_label, 25, 270);
    ui_DropSelectTheme=lv_dropdown_create(ui_Settings2);
    lv_obj_set_size(ui_DropSelectTheme, 150, 45);
    lv_obj_set_pos(ui_DropSelectTheme, 305, 255);
    lv_dropdown_set_options(ui_DropSelectTheme, "NONE\nLOGO");
    lv_obj_add_event_cb(ui_DropSelectTheme, action_theme_changed, LV_EVENT_VALUE_CHANGED, NULL);

}

void ui_Settings2_screen_destroy(void)
{
    if(ui_Settings2) lv_obj_del(ui_Settings2);

    // NULL screen variables
    ui_Settings2 = NULL;
    ui_DropSelectTheme = NULL;
    ui_LabelHysteresis = NULL;
    ui_DropHysteresis = NULL;
    ui_LabelStageStep = NULL;
    ui_DropStageStep = NULL;
    ui_LabelSensorOffset = NULL;
    ui_SpinSensorOffset = NULL;
    ui_BtnOffsetDec = NULL;
    ui_LabelBtnOffsetDec = NULL;
    ui_BtnOffsetInc = NULL;
    ui_LabelBtnOffsetInc = NULL;
    ui_BtnSave2 = NULL;
    ui_LabelBtnSave2 = NULL;
    ui_BtnNext2 = NULL;
    ui_LabelBtnNext2 = NULL;

}

void ui_Settings2_screen_relocalize(void)
{
    // label widgets on screen

}
