// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: HotelRoomThermostat

#include "ui.h"

lv_obj_t * ui_Settings1 = NULL;
lv_obj_t * ui_LabelMinTemp = NULL;
lv_obj_t * ui_DropMinTemp = NULL;
lv_obj_t * ui_LabelMaxTemp = NULL;
lv_obj_t * ui_DropMaxTemp = NULL;
lv_obj_t * ui_LabelMode = NULL;
lv_obj_t * ui_DropMode = NULL;
lv_obj_t * ui_LabelCtrlType = NULL;
lv_obj_t * ui_DropCtrlType = NULL;
lv_obj_t * ui_BtnSave1 = NULL;
lv_obj_t * ui_LabelBtnSave1 = NULL;
lv_obj_t * ui_BtnNext1 = NULL;
lv_obj_t * ui_LabelBtnNext1 = NULL;
// event funtions
void ui_event_Settings1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        settings1_loaded_cb(e);
    }
}

void ui_event_DropMinTemp(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        action_min_temp_changed(e);
    }
}

void ui_event_DropMaxTemp(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        action_max_temp_changed(e);
    }
}

void ui_event_DropMode(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        action_hvac_mode_changed(e);
    }
}

void ui_event_DropCtrlType(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        action_ctrl_type_changed(e);
    }
}

void ui_event_BtnSave1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        action_save_and_exit(e);
    }
}

void ui_event_BtnNext1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Settings2, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Settings2_screen_init);
    }
}

// build funtions

void ui_Settings1_screen_init(void)
{
    ui_Settings1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Settings1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Settings1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Settings1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Settings1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelMinTemp = lv_label_create(ui_Settings1);
    lv_obj_set_width(ui_LabelMinTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelMinTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelMinTemp, 20);
    lv_obj_set_y(ui_LabelMinTemp, 30);
    lv_label_set_text(ui_LabelMinTemp, "Min Temp");

    ui_DropMinTemp = lv_dropdown_create(ui_Settings1);
    lv_dropdown_set_options(ui_DropMinTemp, "10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20\n21\n22\n23\n24");
    lv_obj_set_width(ui_DropMinTemp, 200);
    lv_obj_set_height(ui_DropMinTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DropMinTemp, -20);
    lv_obj_set_y(ui_DropMinTemp, 20);
    lv_obj_set_align(ui_DropMinTemp, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_DropMinTemp, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_LabelMaxTemp = lv_label_create(ui_Settings1);
    lv_obj_set_width(ui_LabelMaxTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelMaxTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelMaxTemp, 20);
    lv_obj_set_y(ui_LabelMaxTemp, 110);
    lv_label_set_text(ui_LabelMaxTemp, "Max Temp");

    ui_DropMaxTemp = lv_dropdown_create(ui_Settings1);
    lv_dropdown_set_options(ui_DropMaxTemp, "25\n26\n27\n28\n29\n30\n31\n32\n33\n34\n35\n36\n37\n38\n39\n40");
    lv_obj_set_width(ui_DropMaxTemp, 200);
    lv_obj_set_height(ui_DropMaxTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DropMaxTemp, -20);
    lv_obj_set_y(ui_DropMaxTemp, 100);
    lv_obj_set_align(ui_DropMaxTemp, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_DropMaxTemp, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_LabelMode = lv_label_create(ui_Settings1);
    lv_obj_set_width(ui_LabelMode, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelMode, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelMode, 20);
    lv_obj_set_y(ui_LabelMode, 190);
    lv_label_set_text(ui_LabelMode, "HVAC Mode");

    ui_DropMode = lv_dropdown_create(ui_Settings1);
    lv_dropdown_set_options(ui_DropMode, "Off\nHeating\nCooling");
    lv_obj_set_width(ui_DropMode, 200);
    lv_obj_set_height(ui_DropMode, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DropMode, -20);
    lv_obj_set_y(ui_DropMode, 180);
    lv_obj_set_align(ui_DropMode, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_DropMode, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_LabelCtrlType = lv_label_create(ui_Settings1);
    lv_obj_set_width(ui_LabelCtrlType, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelCtrlType, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelCtrlType, 20);
    lv_obj_set_y(ui_LabelCtrlType, 270);
    lv_label_set_text(ui_LabelCtrlType, "Control Type");

    ui_DropCtrlType = lv_dropdown_create(ui_Settings1);
    lv_dropdown_set_options(ui_DropCtrlType, "1-Relay\n3-Speed Fan");
    lv_obj_set_width(ui_DropCtrlType, 200);
    lv_obj_set_height(ui_DropCtrlType, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DropCtrlType, -20);
    lv_obj_set_y(ui_DropCtrlType, 260);
    lv_obj_set_align(ui_DropCtrlType, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_DropCtrlType, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_BtnSave1 = lv_btn_create(ui_Settings1);
    lv_obj_set_width(ui_BtnSave1, 140);
    lv_obj_set_height(ui_BtnSave1, 60);
    lv_obj_set_x(ui_BtnSave1, 20);
    lv_obj_set_y(ui_BtnSave1, -20);
    lv_obj_set_align(ui_BtnSave1, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_BtnSave1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnSave1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelBtnSave1 = lv_label_create(ui_BtnSave1);
    lv_obj_set_width(ui_LabelBtnSave1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelBtnSave1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelBtnSave1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelBtnSave1, "SAVE");
    lv_obj_set_style_text_font(ui_LabelBtnSave1, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnNext1 = lv_btn_create(ui_Settings1);
    lv_obj_set_width(ui_BtnNext1, 140);
    lv_obj_set_height(ui_BtnNext1, 60);
    lv_obj_set_x(ui_BtnNext1, -20);
    lv_obj_set_y(ui_BtnNext1, -20);
    lv_obj_set_align(ui_BtnNext1, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_add_flag(ui_BtnNext1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnNext1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelBtnNext1 = lv_label_create(ui_BtnNext1);
    lv_obj_set_width(ui_LabelBtnNext1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelBtnNext1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelBtnNext1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelBtnNext1, "NEXT");
    lv_obj_set_style_text_font(ui_LabelBtnNext1, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_DropMinTemp, ui_event_DropMinTemp, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_DropMaxTemp, ui_event_DropMaxTemp, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_DropMode, ui_event_DropMode, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_DropCtrlType, ui_event_DropCtrlType, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnSave1, ui_event_BtnSave1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnNext1, ui_event_BtnNext1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Settings1, ui_event_Settings1, LV_EVENT_ALL, NULL);

}

void ui_Settings1_screen_destroy(void)
{
    if(ui_Settings1) lv_obj_del(ui_Settings1);

    // NULL screen variables
    ui_Settings1 = NULL;
    ui_LabelMinTemp = NULL;
    ui_DropMinTemp = NULL;
    ui_LabelMaxTemp = NULL;
    ui_DropMaxTemp = NULL;
    ui_LabelMode = NULL;
    ui_DropMode = NULL;
    ui_LabelCtrlType = NULL;
    ui_DropCtrlType = NULL;
    ui_BtnSave1 = NULL;
    ui_LabelBtnSave1 = NULL;
    ui_BtnNext1 = NULL;
    ui_LabelBtnNext1 = NULL;

}

void ui_Settings1_screen_relocalize(void)
{
    // label widgets on screen

}
