// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: HotelRoomThermostat

#include "ui.h"
#include "ui_mode_hold.h"

lv_obj_t * ui_Thermostat = NULL;
lv_obj_t * ui_TileThermostat = NULL;
lv_obj_t * ui_LabelTargetTemp = NULL;
lv_obj_t * ui_ArcTemp = NULL;
lv_obj_t * ui_BtnNextThermostat = NULL;
lv_obj_t * ui_BtnFan = NULL;
lv_obj_t * ui_LabelFanStatus = NULL;
lv_obj_t * ui_BtnPrevThermostat = NULL;
lv_obj_t * ui_LabelRoomTemp = NULL;
lv_obj_t * ui_ImageHeatStatus = NULL;
lv_obj_t * ui_ImageCoolStatus = NULL;
lv_obj_t * ui_LabelActiveFanSpeed = NULL;
// event funtions
void ui_event_Thermostat(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        thermostat_loaded_cb(e);
    }
}

void ui_event_ArcTemp(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        action_arc_temp_changed(e);
    }
}

void ui_event_BtnNextThermostat(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Clean, LV_SCR_LOAD_ANIM_NONE, 100, 0, &ui_Clean_screen_init);
    }
}

void ui_event_BtnFan(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        action_fan_speed_change(e);
    }
}

void ui_event_BtnPrevThermostat(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Main, LV_SCR_LOAD_ANIM_NONE, 100, 0, &ui_Main_screen_init);
    }
}

// build funtions

void ui_Thermostat_screen_init(void)
{
    ui_Thermostat = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Thermostat, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Thermostat, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Thermostat, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TileThermostat = lv_obj_create(ui_Thermostat);
    lv_obj_set_width(ui_TileThermostat, lv_pct(100));
    lv_obj_set_height(ui_TileThermostat, lv_pct(100));
    lv_obj_set_align(ui_TileThermostat, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TileThermostat, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TileThermostat, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TileThermostat, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_TileThermostat, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelTargetTemp = lv_label_create(ui_TileThermostat);
    lv_obj_set_width(ui_LabelTargetTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTargetTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTargetTemp, 7);
    lv_obj_set_y(ui_LabelTargetTemp, -40);
    lv_obj_set_align(ui_LabelTargetTemp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTargetTemp, "22°");
    lv_obj_set_style_text_color(ui_LabelTargetTemp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelTargetTemp, 230, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelTargetTemp, &ui_font_fontinterlight80, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ArcTemp = lv_arc_create(ui_TileThermostat);
    lv_obj_set_width(ui_ArcTemp, 300);
    lv_obj_set_height(ui_ArcTemp, 300);
    lv_obj_set_x(ui_ArcTemp, 0);
    lv_obj_set_y(ui_ArcTemp, -40);
    lv_obj_set_align(ui_ArcTemp, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ArcTemp, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_arc_set_range(ui_ArcTemp, 10, 40);
    lv_arc_set_value(ui_ArcTemp, 22);
    lv_arc_set_bg_angles(ui_ArcTemp, 135, 45);
    lv_obj_set_style_arc_color(ui_ArcTemp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ArcTemp, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_ArcTemp, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_ArcTemp, false, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_ArcTemp, lv_color_hex(0xFF8000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_ArcTemp, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_ArcTemp, 15, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_ArcTemp, true, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_ArcTemp, lv_color_hex(0xFF8000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ArcTemp, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_ArcTemp, 15, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_ArcTemp, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_BtnNextThermostat = lv_btn_create(ui_TileThermostat);
    lv_obj_set_width(ui_BtnNextThermostat, 100);
    lv_obj_set_height(ui_BtnNextThermostat, 100);
    lv_obj_set_x(ui_BtnNextThermostat, 0);
    lv_obj_set_y(ui_BtnNextThermostat, -10);
    lv_obj_set_align(ui_BtnNextThermostat, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_add_flag(ui_BtnNextThermostat, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnNextThermostat, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BtnNextThermostat, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BtnNextThermostat, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnNextThermostat, 35, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_BtnNextThermostat, &ui_img_arrow_forward_ios_48_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_opa(ui_BtnNextThermostat, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BtnNextThermostat, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_BtnNextThermostat, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_BtnNextThermostat, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_BtnNextThermostat, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_BtnNextThermostat, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BtnNextThermostat, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_BtnNextThermostat, 30, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_color(ui_BtnNextThermostat, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_opa(ui_BtnNextThermostat, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_width(ui_BtnNextThermostat, 35, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_spread(ui_BtnNextThermostat, 0, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_BtnFan = lv_btn_create(ui_TileThermostat);
    lv_obj_set_width(ui_BtnFan, 100);
    lv_obj_set_height(ui_BtnFan, 100);
    lv_obj_set_x(ui_BtnFan, 0);
    lv_obj_set_y(ui_BtnFan, -10);
    lv_obj_set_align(ui_BtnFan, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_BtnFan, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnFan, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BtnFan, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BtnFan, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnFan, 35, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_BtnFan, &ui_img_fan_mode_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_opa(ui_BtnFan, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BtnFan, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_BtnFan, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_BtnFan, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_BtnFan, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_BtnFan, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BtnFan, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_BtnFan, 35, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_color(ui_BtnFan, lv_color_hex(0xFFFF00), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_opa(ui_BtnFan, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_width(ui_BtnFan, 35, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_spread(ui_BtnFan, 0, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_LabelFanStatus = lv_label_create(ui_BtnFan);
    lv_obj_set_width(ui_LabelFanStatus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelFanStatus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelFanStatus, 0);
    lv_obj_set_y(ui_LabelFanStatus, 35);
    lv_obj_set_align(ui_LabelFanStatus, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelFanStatus, "Auto");
    lv_obj_set_style_text_color(ui_LabelFanStatus, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelFanStatus, 210, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelFanStatus, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelFanStatus, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BtnPrevThermostat = lv_btn_create(ui_TileThermostat);
    lv_obj_set_width(ui_BtnPrevThermostat, 100);
    lv_obj_set_height(ui_BtnPrevThermostat, 100);
    lv_obj_set_x(ui_BtnPrevThermostat, 0);
    lv_obj_set_y(ui_BtnPrevThermostat, -10);
    lv_obj_set_align(ui_BtnPrevThermostat, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_BtnPrevThermostat, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BtnPrevThermostat, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BtnPrevThermostat, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BtnPrevThermostat, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BtnPrevThermostat, 35, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_BtnPrevThermostat, &ui_img_arrow_back_ios_48_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_opa(ui_BtnPrevThermostat, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_BtnPrevThermostat, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_BtnPrevThermostat, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_BtnPrevThermostat, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_BtnPrevThermostat, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_BtnPrevThermostat, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BtnPrevThermostat, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_BtnPrevThermostat, 30, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_color(ui_BtnPrevThermostat, lv_color_hex(0x0000FF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_opa(ui_BtnPrevThermostat, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_width(ui_BtnPrevThermostat, 35, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_spread(ui_BtnPrevThermostat, 0, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_LabelRoomTemp = lv_label_create(ui_TileThermostat);
    lv_obj_set_width(ui_LabelRoomTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelRoomTemp, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_LabelRoomTemp, "Innen: \n24°C");
    lv_obj_set_style_text_color(ui_LabelRoomTemp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelRoomTemp, 210, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelRoomTemp, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageHeatStatus = lv_img_create(ui_TileThermostat);
    lv_img_set_src(ui_ImageHeatStatus, &ui_img_heating_png);
    lv_obj_set_width(ui_ImageHeatStatus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageHeatStatus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ImageHeatStatus, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_ImageHeatStatus, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageHeatStatus, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_img_recolor(ui_ImageHeatStatus, lv_color_hex(0xFF9800), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_ImageHeatStatus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageCoolStatus = lv_img_create(ui_TileThermostat);
    lv_img_set_src(ui_ImageCoolStatus, &ui_img_cooling_png);
    lv_obj_set_width(ui_ImageCoolStatus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageCoolStatus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ImageCoolStatus, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_ImageCoolStatus, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageCoolStatus, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_img_recolor(ui_ImageCoolStatus, lv_color_hex(0x00BFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_img_recolor_opa(ui_ImageCoolStatus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Independent sibling: updating the speed never changes either mode icon.
    ui_LabelActiveFanSpeed = lv_label_create(ui_TileThermostat);
    lv_obj_set_width(ui_LabelActiveFanSpeed, 48);
    lv_obj_set_align(ui_LabelActiveFanSpeed, LV_ALIGN_TOP_RIGHT);
    lv_obj_set_y(ui_LabelActiveFanSpeed, 54);
    lv_obj_set_style_text_align(ui_LabelActiveFanSpeed, LV_TEXT_ALIGN_CENTER, 0);
    lv_obj_set_style_text_font(ui_LabelActiveFanSpeed, &lv_font_montserrat_18, 0);
    lv_obj_set_style_text_color(ui_LabelActiveFanSpeed, lv_color_hex(0xFFFFFF), 0);
    lv_obj_clear_flag(ui_LabelActiveFanSpeed, LV_OBJ_FLAG_CLICKABLE);
    lv_label_set_text(ui_LabelActiveFanSpeed, "");

    lv_obj_add_event_cb(ui_ArcTemp, ui_event_ArcTemp, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnNextThermostat, ui_event_BtnNextThermostat, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnFan, ui_event_BtnFan, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BtnPrevThermostat, ui_event_BtnPrevThermostat, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Thermostat, ui_event_Thermostat, LV_EVENT_ALL, NULL);
    ui_mode_hold_init();

}

void ui_Thermostat_screen_destroy(void)
{
    if(ui_Thermostat) lv_obj_del(ui_Thermostat);

    // NULL screen variables
    ui_Thermostat = NULL;
    ui_TileThermostat = NULL;
    ui_LabelTargetTemp = NULL;
    ui_ArcTemp = NULL;
    ui_BtnNextThermostat = NULL;
    ui_BtnFan = NULL;
    ui_LabelFanStatus = NULL;
    ui_BtnPrevThermostat = NULL;
    ui_LabelRoomTemp = NULL;
    ui_ImageHeatStatus = NULL;
    ui_ImageCoolStatus = NULL;
    ui_LabelActiveFanSpeed = NULL;

}

void ui_Thermostat_screen_relocalize(void)
{
    // label widgets on screen

}
