// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: HotelRoomThermostat

#ifndef UI_THERMOSTAT_H
#define UI_THERMOSTAT_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Thermostat
extern void ui_Thermostat_screen_init(void);
extern void ui_Thermostat_screen_destroy(void);
extern void ui_Thermostat_screen_relocalize(void);
extern lv_obj_t * ui_Thermostat;
extern void ui_event_Thermostat(lv_event_t * e);
extern lv_obj_t * ui_TileThermostat;
extern lv_obj_t * ui_LabelTargetTemp;
extern void ui_event_ArcTemp(lv_event_t * e);
extern lv_obj_t * ui_ArcTemp;
extern void ui_event_BtnNextThermostat(lv_event_t * e);
extern lv_obj_t * ui_BtnNextThermostat;
extern void ui_event_BtnFan(lv_event_t * e);
extern lv_obj_t * ui_BtnFan;
extern lv_obj_t * ui_LabelFanStatus;
extern void ui_event_BtnPrevThermostat(lv_event_t * e);
extern lv_obj_t * ui_BtnPrevThermostat;
extern lv_obj_t * ui_LabelRoomTemp;
extern lv_obj_t * ui_ImageHeatStatus;
extern lv_obj_t * ui_ImageCoolStatus;
extern lv_obj_t * ui_LabelActiveFanSpeed;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

